### ISSUE TITLE
Is `providers` clear enough in CredentialRequestOptions

### ISSUE THREAD

**Issue by marcoscaceres** [WICG/digital-identities#74]
`CredentialRequestOptions`'s `providers` members identifies the credential requests as being for/of our spec. This is coupled with the fact that `.providers` only works with  `navigator.identity.get()` (that is, `navigator.crendentials.get()` and other methods should ignore `.providers`).  

However, there is a concern that `providers` might be overly generic. 

In Cred Man, other members are:

```WebIDL
dictionary CredentialRequestOptions {   
   FederatedCredentialRequestOptions federated;
   boolean password = false;  
};
```

And so on... we should be following that ("federated", "password") pattern. 

cc @bc-pi

**Comment by marcoscaceres** [comment]
@nsatragno, we could use your insights again from Cred Manager perspective  🙏

**Comment by OR13** [comment]
Can this be phrased as a proposal? Like keep it as is (example1), change it to match CM (example2) ?

**Comment by bc-pi** [comment]
My concern  with `providers` (which I seem to be struggling to articulate and maybe I'm just hopelessly confused) is basically this draft elsewhere has provider as the thing that handles requests. While this thing on `CredentialRequestOptions` is a list of requests. Those request(s) will be handled by providers but the request(s) are not themselves the providers.  To me anyway, calling the member providers suggests that it's something that it's not.

**Comment by nsatragno** [comment]
Normally, the attribute added to the `CredentialRequestOptions` dictionary is expected to match the credential's `[[type]]`, which [so far has always matched the name of the credential interface minus "Credential"](https://w3c.github.io/webappsec-credential-management/#sctn-cred-type-registry). WebAuthn is a bit of an oddball because the `[[type]]` is defined as `public-key`, but the attribute name is `publicKey`.

I would suggest defining your partial dictionary addition like so:

```webidl
partial dictionary CredentialRequestOptions {
  DigitalIdentityRequestOptions digitalIdentity;
};

dictionary DigitalIdentityRequestOptions {
  sequence<IdentityRequestProvider> providers;
};
```

Then, your credential `[[type]]` should be `digitalIdentity`.

An RP would call the API like so:

```js
navigator.identity.get({
  signal: ...,  // optional
  mediation: ...,  // optional
  digitalIdentity: {
    providers: [{protocol, request}, {...}],
  }
});
```

You also need your credential type to inherit from [`Credential`](https://w3c.github.io/webappsec-credential-management/#the-credential-interface), which gives it an `id` and `type`. [There is a high level overview of adding a new credential type on the credman spec](https://w3c.github.io/webappsec-credential-management/#implementation-extension) -- please file an issue if you find bugs on it!

As an aside, I would suggest reevaluating the name of the credential type. It might be confusing to have `identity` and `digitalIdentity` mean very different things!

**Comment by samuelgoto** [comment]
> As an aside, I would suggest reevaluating the name of the credential type. It might be confusing to have identity and digitalIdentity mean very different things!

Yeah, that's what is a bit awkward about `digitalIdentity` indeed ... a `digitalIdentity` inside the `navigator.identity`, that's a lot of identities ...

Separately, `digitalIdentity` would also be fairly close to the `identity` value of `IdentityCredential`, which FedCM uses.

What about another shorter value, like `digital`? or `rwi`? or `wallet`? or `decentralized`?

**Comment by nsatragno** [comment]
> Using `providers` wouldn't technically be web-visible

Not sure I follow here, using it where?

As the option members identifier (i.e. the dictionary key you pass to `navigator.identity.get({})`) it would clearly be visible -- it's what the RP passes the browser!

[[[type]] is also visible](https://w3c.github.io/webappsec-credential-management/#dom-credential-type-slot) and would be important to differentiate between credential types in the same request ([example](https://w3c.github.io/webappsec-credential-management/#examples-password-signin)).

For completeness, the credential class name is used for [feature detection](https://w3c.github.io/webappsec-credential-management/#implementation-authors).

You really want to be consistent here to avoid footguns, especially if you envision a future where different credential types can be returned with the same request.

**Comment by pkotwicz** [comment]
I like Sam's suggestion of

```
dictionary CredentialRequestOptions {   
   RwiCredentialRequestOptions rwi;
};
```

What do other people think?

**Comment by samuelgoto** [comment]
@marcoscaceres and I met together and I think we arrived at something that strikes the right balance: `digital`. 

For example:

```javascript
await navigator.identity.get({
  digital: {
     // ....
  }
});
```

Although `digital` is a bit broad (what isn't digital, after all), it seemed nice that it reuses the language that we are seeing at the [Digital Credentials Protocols Working Group](https://openid.net/wg/digital-credentials-protocols/) at OIDF.

A few alternatives that we considered that we think strike a worse balance in comparison to `digital` (in order of things we like more to less):

- `verified` (or `vc`): we thought that `verified` meaningfully represents what's most intrinsic about the credential, but`VerifiedCredential` would create confusion with [this](https://www.w3.org/TR/vc-data-model/#what-is-a-verifiable-credential) definition that's widely used.
- `digitalIdentity`: too many identities (e.g. `navigator.identity.get({digitalIdentity: {}})`)
- `issued` or `held`: seemed a bit awkward
- `rwi`: it is hard to define what we mean by "real world" (e.g. are Google accounts "real world"?)
- `government`: too narrow
- `provides`: inconsistent with the Credential Manager API spec and design

This choice is currently represented in the last spec draft [here](https://wicg.github.io/digital-identities/#the-digital-member).

Closing this issue here, feel free to reopen if you strongly disagree (or have a better alternative) and we can revisit this.
