### ISSUE TITLE
Should `request` be an `object` in addition to a `DOMString`?

### ISSUE THREAD

**Issue by samuelgoto** [WICG/digital-identities#75]
The `request` field is [currently](https://wicg.github.io/digital-identities/#the-request-member) a `DOMString`, which allows `request` to be fully extensible.

For "well-known" `protocols`, should we make `request` also take a `object`, such that we can reuse the WebIDL's parsing/type checking?

On one hand, we'd get type checking, but on the other hand, we'd make it less extensible by dropping unknown fields on the ground. Unclear if that's a feature or a bug.

@marcoscaceres FYI

**Comment by marcoscaceres** [comment]
I feel somewhat strongly that this should initially be an object (though we could convert it to an object internally), but I'd personally like to see it initially be an object because there are a lot security advantages to doing that (mostly because we can do all the conversions to IDL as the object comes in). 

If the model breaks down, then we should switch to DOMString. The determine factor here will be the structure of the request though (as dictated by whatever we put into the Registry as the mandated request format/protocol).
